sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t esak248/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true esak248/react-test npm test

after_success:
  - docker build -t esak248/multi-client ./client
  - docker build -t esak248/multi-nginx ./nginx
  - docker build -t esak248/multi-server ./server
  - docker build -t esak248/multi-worker ./worker
  #docker hub 에 이미지를 올리기 위해 로그인 한다.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push esak248/multi-client
  - docker push esak248/multi-nginx
  - docker push esak248/multi-server
  - docker push esak248/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: MultiDocker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-ap-northeast-2-878392923027
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY